# Generated by Django 2.2.5 on 2019-09-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
