# Generated by Django 2.2.5 on 2019-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisadores', '0002_pesquisador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='foto',
            field=models.ImageField(upload_to='pesquisador_fotos'),
        ),
    ]
