# Generated by Django 2.2.5 on 2019-09-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='pesquisador_fotos')),
                ('instituicao_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(max_length=500)),
                ('objetivo', models.IntegerField()),
                ('arrecadado', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='projeto_fotos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pesquisador')),
            ],
        ),
    ]
