# Generated by Django 2.2.5 on 2019-09-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pesquisador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='foto',
        ),
    ]
